#bind mounts
volumes: #stored on host machine and persist beyond lifecycle of containers
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      device: /home/nhorta-g/data/mariadb
      o: bind #share data between host and container, access, modify info form host and container
      type: none

  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      device: /home//nhorta-g/data/wordpress
      o: bind
      type: none

#user defined bridge network by default
#containers can use their service names to communicate with each other
networks:
  netNuno:
    name: netNuno

services:
  mariadb:
    image: mariadb #docker build
    container_name: mariadb
    build: ./requirements/mariadb #build image
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    networks:
      - netNuno #docker compose up
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443" #HTTPS (ssl) traffic
    depends_on:
      - wordpress #nginx handles incoming HTTP/HTTPS requests and forwards them to WordPress
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - netNuno
    restart: always

  wordpress:
    image: wordpress
    container_name: wordpress
    build: ./requirements/wordpress
    depends_on:
      - mariadb #wp needs data base
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - netNuno
    restart: always